// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyWebApiKeyForProjectSetup123',
    appId: '1:177276457465:web:dummyAppId',
    messagingSenderId: '177276457465',
    projectId: 'gjandasher-shiptracker',
    authDomain: 'gjandasher-shiptracker.firebaseapp.com',
    storageBucket: 'gjandasher-shiptracker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDummyAndroidApiKeyForProjectSetup123',
    appId: '1:177276457465:android:dummyAppId',
    messagingSenderId: '177276457465',
    projectId: 'gjandasher-shiptracker',
    storageBucket: 'gjandasher-shiptracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyIosApiKeyForProjectSetup123',
    appId: '1:177276457465:ios:dummyAppId',
    messagingSenderId: '177276457465',
    projectId: 'gjandasher-shiptracker',
    storageBucket: 'gjandasher-shiptracker.appspot.com',
    iosBundleId: 'com.aistudio.shiptracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyMacosApiKeyForProjectSetup123',
    appId: '1:177276457465:ios:dummyAppId',
    messagingSenderId: '177276457465',
    projectId: 'gjandasher-shiptracker',
    storageBucket: 'gjandasher-shiptracker.appspot.com',
    iosBundleId: 'com.aistudio.shiptracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummyWindowsApiKeyForProjectSetup123',
    appId: '1:177276457465:web:dummyAppId',
    messagingSenderId: '177276457465',
    projectId: 'gjandasher-shiptracker',
    authDomain: 'gjandasher-shiptracker.firebaseapp.com',
    storageBucket: 'gjandasher-shiptracker.appspot.com',
  );
}
